version: '3'
    
services:
  async-api:
    build: .
    container_name: async-api
    command: bash -c "python /opt/app/src/main.py"
    env_file: 
      - .env.docker
    ports:
      - "${ASYNC_API_PORT}:${ASYNC_API_PORT}"
    networks:
      - development-network
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: elasticsearch:8.5.0
    container_name: elasticsearch-async-api
    env_file:
      - .env.docker
    healthcheck:
      test: curl -s http://127.0.0.1:${ES_PORT} >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    environment:
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
    ports:
      - "${ES_PORT}:${ES_PORT}"
    networks:
      - development-network
    restart: always

  redis:
    image: redis:7.0.5
    container_name: redis-async-api
    env_file:
      - .env.docker
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - development-network

networks:
  development-network:
    name: development-network
    external: false