version: '3'
    
services:
  async_api:
    build:
      context: async-api
      dockerfile: Dockerfile
    container_name: async_api
    volumes:
      - ./.env:/opt/app/src/.env
    expose:
      - "${ASYNC_API_PORT}"
    networks:
      - production_network
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy

  auth:
    build:
      context: auth
      dockerfile: Dockerfile
    container_name: auth
    volumes:
      - ./.env:/opt/app/.env
    expose:
      - "${AUTH_PORT}"
    networks:
      - production_network
    depends_on:
      - postgres
      - redis
      - jaeger
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger_async_api
    ports:
      - "${JAEGER_PORT}:${JAEGER_PORT}/udp"
      - "16686:16686"
    networks:
      - production_network

  elasticsearch:
    image: elasticsearch:8.5.1
    container_name: elasticsearch_async_api
    healthcheck:
      test: curl -s http://127.0.0.1:${ES_PORT} >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    environment:
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
    expose:
      - "${ES_PORT}"
    networks:
      - production_network
    restart: always

  redis:
    image: redis:7.0.5
    container_name: redis_async_api
    restart: always
    expose:
      - "${REDIS_PORT}"
    networks:
      - production_network

  postgres:
    image: postgres:15.1
    container_name: postgres_async_api
    expose:
      - "${PG_PORT}"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - production_network

  etl:
    container_name: etl_async_api
    build:
      context: etl/postgres_to_es
      dockerfile: Dockerfile
    volumes:
    - ./.env:/opt/app/.env
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - production_network

  admin_panel:
    container_name: admin_panel_async_api
    build:
      context: admin-panel/movies
      dockerfile: Dockerfile
    expose:
      - "${ADM_PANEL_PORT}"
    restart: always
    volumes:
      - ./.env:/opt/app/.env
      - ./admin-panel/movies/static:/opt/app/static
    depends_on:
      - postgres
    networks:
      - production_network

  nginx:
    image: nginx:1.23.2
    container_name: nginx_async_api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./admin-panel/movies/static:/static
    depends_on:
      - admin_panel
      - async_api
    ports:
      - "80:80"
    networks:
      - production_network
    restart: always

  ugc:
    container_name: ugc
    build:
      context: ugc
      dockerfile: Dockerfile
    expose:
      - "${UGC_PORT}"
    volumes:
      - ./.env:/opt/app/.env
    depends_on:
      - auth
      - zookeeper
      - broker
      - broker-ui
    restart: always
    networks:
      - production_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    restart: always
    expose:
      - "${ZOOKEEPER_PORT}"
    environment:
      - ZOOKEEPER_CLIENT_PORT=${ZOOKEEPER_PORT}
      - ZOOKEEPER_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - production_network

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    restart: always
    expose:
      - "${BROKER_INSIDE_PORT}"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:${ZOOKEEPER_PORT}
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_ADVERTISED_HOST_NAME=broker
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=INSIDE://:${BROKER_INSIDE_PORT}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://broker:${BROKER_INSIDE_PORT}
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
    networks:
      - production_network

  broker-ui:
    image: obsidiandynamics/kafdrop:3.30.0
    container_name: broker-ui
    ports:
      - "${BROKER_UI_PORT}:${BROKER_UI_PORT}"
    depends_on:
      - broker
    environment:
      - KAFKA_BROKERCONNECT=broker:${BROKER_INSIDE_PORT}
      - SERVER_PORT=${BROKER_UI_PORT}
    networks:
      - production_network


networks:
  production_network:
    name: production_network
    external: false