version: '3.5'

services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    hostname: clickhouse_test
    ports:
      - "8123:8123"
      - "9000:9000"
      
  vertica:
    image: jbfavre/vertica:latest
    hostname: vertica
    ports:
      - "5433:5433"

  mongo:
    image: mongo:5.0.7-focal
    container_name: mongo_test
    hostname: mongo_test
    restart: always
    ports:
      - "27017:27017"