# Generated by Django 4.0 on 2022-01-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='transport',
            field=models.CharField(choices=[('sms', 'Sms'), ('email', 'Email')], default='email', max_length=50),
        ),
        migrations.AlterField(
            model_name='mailingtask',
            name='status',
            field=models.CharField(choices=[('pending', 'В очередь на отправку'), ('done', 'Отправлено'), ('cancelled', 'Отменено')], default='pending', max_length=250),
        ),
    ]
