# Generated by Django 4.0.1 on 2022-02-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_template_transport_alter_mailingtask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='code',
            field=models.CharField(choices=[('welcome_letter', 'Приветствие нового пользователя'), ('weekly_movies_selection', 'Еженедельная подборка фильмов'), ('monthly_personal_statistic', 'Ежемесячная персональная статистика')], max_length=50),
        ),
    ]
