services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.4.2.1
    container_name: ch_test
    hostname: ch_test
    restart: always
    volumes:
      - ./volumes/ch_db:/var/lib/clickhouse/
      - ./volumes/ch_log:/val/log/clickhouse-server/
    ports:
      - "8123:8123"
      - "9000:9000"

  mongo:
    image: mongo:5.0.7-focal
    container_name: mongo_test
    hostname: mongo_test
    restart: always
    volumes:
      - ./volumes/mongo_db:/data/db
    ports:
      - "27017:27017"
