"""init

Revision ID: d5e08068f181
Revises: 
Create Date: 2023-01-24 17:00:02.473575

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5e08068f181'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='auth'
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('login'),
    schema='auth'
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc'),
    schema='public'
    )
    op.create_table('login_histories',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='auth'
    )
    op.create_table('user_roles',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('role_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id'),
    schema='auth'
    )
    with op.batch_alter_table('auth_group_permissions', schema=None) as batch_op:
        batch_op.drop_constraint('auth_group_permissio_permission_id_84c5c92e_fk_auth_perm', type_='foreignkey')
        batch_op.drop_constraint('auth_group_permissions_group_id_b120cbf9_fk_auth_group_id', type_='foreignkey')
        batch_op.create_foreign_key('auth_group_permissio_permission_id_84c5c92e_fk_auth_perm', 'auth_permission', ['permission_id'], ['id'], referent_schema='public', initially='DEFERRED', deferrable=True)
        batch_op.create_foreign_key('auth_group_permissions_group_id_b120cbf9_fk_auth_group_id', 'auth_group', ['group_id'], ['id'], referent_schema='public', initially='DEFERRED', deferrable=True)

    with op.batch_alter_table('auth_permission', schema=None) as batch_op:
        batch_op.drop_constraint('auth_permission_content_type_id_2f476e4b_fk_django_co', type_='foreignkey')
        batch_op.create_foreign_key('auth_permission_content_type_id_2f476e4b_fk_django_co', 'django_content_type', ['content_type_id'], ['id'], referent_schema='public', initially='DEFERRED', deferrable=True)

    with op.batch_alter_table('auth_user_groups', schema=None) as batch_op:
        batch_op.drop_constraint('auth_user_groups_user_id_6a12ed8b_fk_auth_user_id', type_='foreignkey')
        batch_op.drop_constraint('auth_user_groups_group_id_97559544_fk_auth_group_id', type_='foreignkey')
        batch_op.create_foreign_key('auth_user_groups_user_id_6a12ed8b_fk_auth_user_id', 'auth_user', ['user_id'], ['id'], referent_schema='public', initially='DEFERRED', deferrable=True)
        batch_op.create_foreign_key('auth_user_groups_group_id_97559544_fk_auth_group_id', 'auth_group', ['group_id'], ['id'], referent_schema='public', initially='DEFERRED', deferrable=True)

    with op.batch_alter_table('auth_user_user_permissions', schema=None) as batch_op:
        batch_op.drop_constraint('auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id', type_='foreignkey')
        batch_op.drop_constraint('auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm', type_='foreignkey')
        batch_op.create_foreign_key('auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm', 'auth_permission', ['permission_id'], ['id'], referent_schema='public', initially='DEFERRED', deferrable=True)
        batch_op.create_foreign_key('auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id', 'auth_user', ['user_id'], ['id'], referent_schema='public', initially='DEFERRED', deferrable=True)

    with op.batch_alter_table('django_admin_log', schema=None) as batch_op:
        batch_op.drop_constraint('django_admin_log_content_type_id_c4bce8eb_fk_django_co', type_='foreignkey')
        batch_op.drop_constraint('django_admin_log_user_id_c564eba6_fk_auth_user_id', type_='foreignkey')
        batch_op.create_foreign_key('django_admin_log_user_id_c564eba6_fk_auth_user_id', 'auth_user', ['user_id'], ['id'], referent_schema='public', initially='DEFERRED', deferrable=True)
        batch_op.create_foreign_key('django_admin_log_content_type_id_c4bce8eb_fk_django_co', 'django_content_type', ['content_type_id'], ['id'], referent_schema='public', initially='DEFERRED', deferrable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('django_admin_log', schema=None) as batch_op:
        batch_op.drop_constraint('django_admin_log_content_type_id_c4bce8eb_fk_django_co', type_='foreignkey')
        batch_op.drop_constraint('django_admin_log_user_id_c564eba6_fk_auth_user_id', type_='foreignkey')
        batch_op.create_foreign_key('django_admin_log_user_id_c564eba6_fk_auth_user_id', 'auth_user', ['user_id'], ['id'], initially='DEFERRED', deferrable=True)
        batch_op.create_foreign_key('django_admin_log_content_type_id_c4bce8eb_fk_django_co', 'django_content_type', ['content_type_id'], ['id'], initially='DEFERRED', deferrable=True)

    with op.batch_alter_table('auth_user_user_permissions', schema=None) as batch_op:
        batch_op.drop_constraint('auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id', type_='foreignkey')
        batch_op.drop_constraint('auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm', type_='foreignkey')
        batch_op.create_foreign_key('auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm', 'auth_permission', ['permission_id'], ['id'], initially='DEFERRED', deferrable=True)
        batch_op.create_foreign_key('auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id', 'auth_user', ['user_id'], ['id'], initially='DEFERRED', deferrable=True)

    with op.batch_alter_table('auth_user_groups', schema=None) as batch_op:
        batch_op.drop_constraint('auth_user_groups_group_id_97559544_fk_auth_group_id', type_='foreignkey')
        batch_op.drop_constraint('auth_user_groups_user_id_6a12ed8b_fk_auth_user_id', type_='foreignkey')
        batch_op.create_foreign_key('auth_user_groups_group_id_97559544_fk_auth_group_id', 'auth_group', ['group_id'], ['id'], initially='DEFERRED', deferrable=True)
        batch_op.create_foreign_key('auth_user_groups_user_id_6a12ed8b_fk_auth_user_id', 'auth_user', ['user_id'], ['id'], initially='DEFERRED', deferrable=True)

    with op.batch_alter_table('auth_permission', schema=None) as batch_op:
        batch_op.drop_constraint('auth_permission_content_type_id_2f476e4b_fk_django_co', type_='foreignkey')
        batch_op.create_foreign_key('auth_permission_content_type_id_2f476e4b_fk_django_co', 'django_content_type', ['content_type_id'], ['id'], initially='DEFERRED', deferrable=True)

    with op.batch_alter_table('auth_group_permissions', schema=None) as batch_op:
        batch_op.drop_constraint('auth_group_permissions_group_id_b120cbf9_fk_auth_group_id', type_='foreignkey')
        batch_op.drop_constraint('auth_group_permissio_permission_id_84c5c92e_fk_auth_perm', type_='foreignkey')
        batch_op.create_foreign_key('auth_group_permissions_group_id_b120cbf9_fk_auth_group_id', 'auth_group', ['group_id'], ['id'], initially='DEFERRED', deferrable=True)
        batch_op.create_foreign_key('auth_group_permissio_permission_id_84c5c92e_fk_auth_perm', 'auth_permission', ['permission_id'], ['id'], initially='DEFERRED', deferrable=True)

    op.drop_table('user_roles', schema='auth')
    op.drop_table('login_histories', schema='auth')
    op.drop_table('alembic_version', schema='public')
    op.drop_table('users', schema='auth')
    op.drop_table('roles', schema='auth')
    # ### end Alembic commands ###
