# Generated by Django 4.1.7 on 2023-04-15 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("card_type", models.CharField(max_length=20, null=True)),
                ("expire", models.CharField(max_length=7, null=True)),
                ("last4", models.CharField(max_length=4)),
                ("first6", models.CharField(max_length=6, null=True)),
                ("payment_method_id", models.UUIDField()),
                (
                    "provider",
                    models.CharField(
                        choices=[("yookassa", "ЮKassa")],
                        default="yookassa",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("week", "week"),
                            ("month", "month"),
                            ("year", "year"),
                        ],
                        default="month",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("trial_period", models.BooleanField(default=False)),
                (
                    "trial_period_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("week", "week"),
                            ("month", "month"),
                            ("year", "year"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("next_tariff_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("waiting", "waiting"),
                            ("canceled", "canceled"),
                            ("no_auto_payment", "no auto payment"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="billing.paymentmethod",
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="billing.tariff",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("idempotency_key", models.UUIDField(null=True)),
                ("payment_id", models.UUIDField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("succeeded", "succeeded"),
                            ("canceled", "canceled"),
                            ("waiting", "waiting"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bills",
                        to="billing.paymentmethod",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
