# Generated by Django 4.1.7 on 2023-04-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="provider",
            field=models.CharField(
                choices=[("ukassa", "ukassa")], default="ukassa", max_length=10
            ),
        ),
    ]
