# Generated by Django 4.1.7 on 2023-03-13 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("type", models.CharField(choices=[("email", "email")], max_length=20)),
            ],
            options={
                "db_table": "templates",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В очереди на отправку"),
                            ("done", "Отправлено"),
                            ("canceled", "Отмненено"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default={},
                        help_text="For example, you can fill film ids, user ids or user roles",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("send_immediately", "Отправить сразу"),
                            ("regular_mailing", "Регулярная рассылка"),
                        ],
                        default="send_immediately",
                        max_length=50,
                    ),
                ),
                (
                    "crontab",
                    models.JSONField(
                        blank=True,
                        help_text="Fill crontab like this: https://docs.celeryq.dev/en/stable/userguide/periodic-tasks.html#crontab-schedules",
                        null=True,
                    ),
                ),
                ("scheduled_datetime", models.DateTimeField(blank=True, null=True)),
                ("execution_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.template",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
            },
        ),
    ]
